### ISSUE TITLE
v1.4.0 Change Log

### ISSUE THREAD

**Issue by yb199478** [CatLib/Core#132]
**框架相关**

- [x] 代码标准规范调整：只有在引导流程完成后才能进行服务构建操作(#180 )
- [x] `Application`代码优化(#181 )
- [x] `Application.Register`增加强制注册支持，允许在已注册服务提供者的基础上强制注册(#184 )

**辅助函数相关**

- [x] `Arr`增加`Test`函数，支持对数组进行自定义检查(#178 )
- [x] `Arr`增加`Set`函数，允许替换匹配值或者在尾部增加替换值(#190 )
- [x] `Arr`中的`Filter`函数，允许传入一个期望值来决定结果集(#196 )
- [x] `Str`增加`Is`重载，允许对于数组类型的模式进行匹配(#179 )
- [x] `Str`增加`JoinList`函数，允许顺序组合给定的字符串数组(#195 )
- [x] `Str`增加`Levenshtein`函数，允许计算两个字符串之间的近似度(#194 )
- [x] `Str`增加`Space`常量代表一个含有空格的空字符串(#197 )
- [x] `Str`中的`Pad`函数增加拓展并且标记旧的格式为已过时(#198 )
- [x] `IContainer.Flash` 将会在2.0版本中被移除(#193 ).

**其他**

- [x] `增加CHANGELOG`(#185 )
- [x] 单元测试项目升级到4.0 framework(#191 )
